# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'StockInfo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StockInfo
   pod "SwiftSpinner"
  pod 'Alamofire'
  pod 'SwiftyJSON', '~> 4.0'

end
